### ISSUE TITLE
ATEM macro list does not refresh after restart

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Client#155]
When you restart the client while working with macro's 
the list becomes empty. only newly added macro's will appear afterwards.
after saving the mixer state and restoring the mixer all macro's reappear.
all earlier made rundown items do work.

**Comment by Zebiolo** [comment]
I can't reproduce this issue. Can you describe it in more detail?

**Comment by mauricev78** [comment]
i have 2 setup's where i am experiencing this.
1 is with 
2x 1M/E ATEM production studio 4K
the other with 
2x 1M/E ATEM production studio 4K
2x 2M/E ATEM production studio 4K

In Both setup's the mixers stay on 24/7 but the client is switched off every evening.
When starting up the client again with a earlier saved rundown. The macro's are gone in the dropdown menu on the right. but things are still functioning (soo they are there but they don't show up).
You can now not make new cue's with earlier made macro's.
after saving the mixer state and restoring the mixer all macro's from that mixer reappear.
macro's made after startup of the client show up as normal.

i am testing in the office on this moment with a ATEM television studio and this error does not show up.
it seems to have something to do with the model/type or maybe because i am using more then one mixer ???  Hopefully i have a new 2M/E on my test bench tommorow  soo i will do some more tests thuis week. thanks for looking into this.

**Comment by Zebiolo** [comment]
Which version / revision are you using?

**Comment by mauricev78** [comment]
Hi just checking stuff on the moment.
tested several revisions. 
But even on 65fe0cb845 (the latest on the moment) it is happening.
some test showed me it only happens on the Production Studio 4K's 
on the Television Studio everything works as expected.
other thing is that it does not happen in OSX ?

**Comment by Zebiolo** [comment]
This issue was a bit tricky to track down :)

What you experience is due to a too small receive buffer between Windows AFD (winsock driver) and the TCP/IP stack. The issue may occur due to high network bandwidth. In our case, because we do not read the incoming UDP packages fast enough.

This is a known problem in Windows XP and Windows 7. I can not reproduce it in Windows 8, Windows 10, Linux or Mac.

The solution is quite simple. Increase the receive buffer for the AFD driver. Add the following DWORD registry keys:

[HKEY_LOCAL_MACHINE \SYSTEM \CurrentControlSet \Services \Afd \Parameters]
DefaultReceiveWindow = 16384
DefaultSendWindow = 16384

You need to reboot for the changes to take effect.

**Comment by mauricev78** [comment]
Thanks Zebilo

I did not have the opportunity yet to check it
but will do ASAP
