### ISSUE TITLE
Image browse button

### ISSUE THREAD

**Issue by didikunz** [CasparCG/Client#240]
Would be nice, if the "New Template Data" could have a "Browse..." button, that allow to select an (image-) file. It would then add the image URL to the Value area.

![grab1](https://user-images.githubusercontent.com/6048776/33219549-19824c7e-d143-11e7-992d-9e6623614db7.png)

**Comment by dotarmin** [comment]
I'm trying to understand if the path would be relative to the users computer or to the server? 
Should the user manually "browse" to the server using the explorer|files|finder window and select an image and then use that path as value or should the user select an image on local computer?

/Armin

**Comment by didikunz** [comment]
Good point. On my systems the server is normally running on the same machine as the client. So this would not matter. If the sever runns on another machine, we could hide the browse button, as it does not make much sense then.

**Comment by dotarmin** [comment]
And off course, we have that scenario  as well, when server and client is running on the same machine just as you wrote. I forgot about that kind of setup because I'm not used to run server and client on same host. 

There is just one thing I'm trying to solve in my head, how would this work if you have two servers mapped under client settings, one on same host as the server and another one server that's on a totally different host. What would happen with the browse button then? Should the button be visible/hidden depending on server selected then? 

I think users would be confused when the Browse button is visible/hidden depending on server selected for a specific template item in the rundown. Then another aspect is the shadow server feature available, if used, then we are back to this scenario with one server on same host as client and one server on another host.

/Armin

**Comment by didikunz** [comment]
In the case where more than one server is available I would hide the button for all items, or gray it out on items, that are set to run on the remote server. The problem then is, that it fails, when the user add such filename data and later change the item to the other server, so the best would probably be, to only show the button, when there is only one localhost server. The feature is more meant as a shortcut to quickly format these filenames for testing stuff durring template development.

**Comment by dotarmin** [comment]
I can't see how this would be implemented in a consistent way having end users (new as pro) in mind without making them confused. Sometimes it's there and sometimes it isn't. I'm closing this issue because I can't see how it can be applied in a convenient way.

**Comment by TracyPeterson** [comment]
Or make it a checkbox selection of how you want it to relate.

I'd say most of the time you could create an  "img" directory in "media"
and have it operate there

I like the idea
